# Generated by Django 4.2.3 on 2023-07-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
        migrations.CreateModel(
            name='Categoria',
            fields=[
                
                ('idCategoria', models.IntegerField(primary_key=True, verbose_name="Id de categoría")),
                ('categoria', models.CharField(max_length=50,null=False))               
            ],
        ),
        
        
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('CodigoProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo Producto')),
                ('categoria', models.CharField(max_length=80, verbose_name='Categoria')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre Producto')),
                ('descripcion', models.CharField(max_length=120, verbose_name='Descripcion')),
                ('precio', models.IntegerField()),
                ('descuentoof', models.DecimalField(decimal_places=1, max_digits=3)),
                ('descuentosus', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=80, verbose_name='Apellido')),
                ('edad', models.IntegerField()),
                ('email', models.CharField(max_length=40, verbose_name='Correo')),
                ('direccion', models.CharField(max_length=120, verbose_name='Direccion')),
            ],
        ),
    ]
