# Generated by Django 4.2.3 on 2023-07-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilusuario_delete_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=80, verbose_name='Categoria')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
