# Generated by Django 4.2.3 on 2023-07-11 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_remove_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='id',
        ),
        migrations.AddField(
            model_name='categoria',
            name='idCategoria',
            field=models.IntegerField(default=2, primary_key=True, serialize=False, verbose_name='Id de categoría'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='sinfoto.jpg', upload_to='images/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
    ]
